import {NarratorObject} from "./NarratorObject"; 
import {ImageObject} from "./ImageObject"; 
import {CopyrightObject} from "./CopyrightObject"; 
import {AuthorObject} from "./AuthorObject"; 
export type AudiobookBase = {
authors: AuthorObject[];
available_markets: string[];
copyrights: CopyrightObject[];
description: string;
html_description: string;
edition?: string;
explicit: boolean;
external_urls: ;
href: string;
id: string;
images: ImageObject[];
languages: string[];
media_type: string;
name: string;
narrators: NarratorObject[];
publisher: string;
type: string;
uri: string;
total_chapters: number;
};